Insert INTO product (name,imgUrl,price) Values ('Frozen HTC10','HTC10-frozen.png',0);
Insert INTO product (name,imgUrl,price) Values ('Star Wars HTC10','HTC10-StarWars.png',0);
Insert INTO product (name,imgUrl,price) Values ('Sillicon Valley HTC10','HTC10-SiliconV.png',0);
Insert INTO product (name,imgUrl,price) Values ('Avengers HTC10','HTC10-Avengers.png',0);
Insert INTO product (name,imgUrl,price) Values ('Game of thrones HTC10','HTC10-GOT.png',0);
Insert INTO product (name,imgUrl,price) Values ('Star Wars iPhone','IPhone6-StarWars.png',0);
Insert INTO product (name,imgUrl,price) Values ('Sillicon Valley iPhone','IPhone6-SiliconeV.png',0);
Insert INTO product (name,imgUrl,price) Values ('Avengers iPhone','IPhone6-Avengers.png',0);
Insert INTO product (name,imgUrl,price) Values ('Game of thrones iPhone','IPhone6-GOT.png',0);
Insert INTO product (name,imgUrl,price) Values ('Frozen iPhone','IPhone6-frozen.png',0);