Insert INTO products (name,imageUrl,availableStock,price) Values ('Frozen HTC10','HTC10-frozen.png',40,5.99);
Insert INTO products (name,imageUrl,availableStock,price) Values ('Star Wars HTC10','HTC10-StarWars.png',21,5.99);
Insert INTO products (name,imageUrl,availableStock,price) Values ('Sillicon Valley HTC10','HTC10-SiliconV.png',0,5.49);
Insert INTO products (name,imageUrl,availableStock,price) Values ('Avengers HTC10','HTC10-Avengers.png',34,5.49);
Insert INTO products (name,imageUrl,availableStock,price) Values ('Game of thrones HTC10','HTC10-GOT.png',1,5.99);
Insert INTO products (name,imageUrl,availableStock,price) Values ('Star Wars iPhone','IPhone6-StarWars.png',5,4.99);
Insert INTO products (name,imageUrl,availableStock,price) Values ('Sillicon Valley iPhone','IPhone6-SiliconeV.png',0,4.99);
Insert INTO products (name,imageUrl,availableStock,price) Values ('Avengers iPhone','IPhone6-Avengers.png',23,4.99);
Insert INTO products (name,imageUrl,availableStock,price) Values ('Game of thrones iPhone','IPhone6-GOT.png',12,4.49);
Insert INTO products (name,imageUrl,availableStock,price) Values ('Frozen iPhone','IPhone6-frozen.png',9,4.49);
